# Generated by Claude Code

import importlib.util
import shutil
from pathlib import Path

_mod_path = Path(__file__).resolve().parent.parent / "sync-symlinks.py"
_spec = importlib.util.spec_from_file_location("sync_symlinks", _mod_path)
sync_symlinks = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(sync_symlinks)


def plugins_root(tmp_path: Path) -> Path:
    plugins_dir = tmp_path / "plugins"
    plugins_dir.mkdir()
    return plugins_dir


def claude_root(tmp_path: Path) -> Path:
    return tmp_path / ".claude"


def make_skill(plugins_dir: Path, plugin: str, name: str) -> Path:
    skill_dir = plugins_dir / plugin / "skills" / name
    skill_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text(f"# {name}\n")
    return skill_dir


def make_command(plugins_dir: Path, plugin: str, name: str) -> Path:
    commands_dir = plugins_dir / plugin / "commands"
    commands_dir.mkdir(parents=True, exist_ok=True)
    command_file = commands_dir / f"{name}.md"
    command_file.write_text(f"# {name}\n")
    return command_file


# -- discover_category_items -------------------------------------------------


class TestDiscoverCategoryItems:
    def test_finds_skill_across_plugins(self, tmp_path):
        plugins = plugins_root(tmp_path)
        make_skill(plugins, "core", "commit")
        make_skill(plugins, "ponytail", "ponytail")

        expected = sync_symlinks.discover_category_items(plugins, "skills")

        assert set(expected) == {"commit", "ponytail"}
        assert expected["commit"] == plugins / "core" / "skills" / "commit"

    def test_ignores_skill_dir_without_skill_md(self, tmp_path):
        plugins = plugins_root(tmp_path)
        (plugins / "core" / "skills" / "not-a-skill").mkdir(parents=True)

        expected = sync_symlinks.discover_category_items(plugins, "skills")

        assert expected == {}

    def test_finds_command_files(self, tmp_path):
        plugins = plugins_root(tmp_path)
        make_command(plugins, "core", "chat")

        expected = sync_symlinks.discover_category_items(plugins, "commands")

        assert expected == {"chat.md": plugins / "core" / "commands" / "chat.md"}

    def test_conflict_across_plugins_is_skipped_with_warning(self, tmp_path, capsys):
        plugins = plugins_root(tmp_path)
        make_skill(plugins, "core", "commit")
        make_skill(plugins, "ponytail", "commit")

        expected = sync_symlinks.discover_category_items(plugins, "skills")

        assert expected == {}
        assert "warning" in capsys.readouterr().err


# -- sync_category ------------------------------------------------------------


class TestSyncCategory:
    def test_creates_missing_symlink(self, tmp_path):
        plugins = plugins_root(tmp_path)
        make_skill(plugins, "core", "commit")
        claude_dir = claude_root(tmp_path)

        reports = sync_symlinks.sync_category(plugins, claude_dir, "skills")

        link = claude_dir / "skills" / "commit"
        assert link.is_symlink()
        assert link.resolve() == (plugins / "core" / "skills" / "commit").resolve()
        assert reports == ["created skills/commit"]

    def test_leaves_correct_symlink_alone(self, tmp_path):
        plugins = plugins_root(tmp_path)
        make_skill(plugins, "core", "commit")
        claude_dir = claude_root(tmp_path)
        sync_symlinks.sync_category(plugins, claude_dir, "skills")

        reports = sync_symlinks.sync_category(plugins, claude_dir, "skills")

        assert reports == ["up to date skills/commit"]

    def test_relinks_symlink_pointing_at_wrong_target(self, tmp_path):
        plugins = plugins_root(tmp_path)
        make_skill(plugins, "core", "commit")
        claude_dir = claude_root(tmp_path)
        skills_dir = claude_dir / "skills"
        skills_dir.mkdir(parents=True)
        (skills_dir / "commit").symlink_to(tmp_path / "elsewhere", target_is_directory=True)

        reports = sync_symlinks.sync_category(plugins, claude_dir, "skills")

        link = skills_dir / "commit"
        assert link.resolve() == (plugins / "core" / "skills" / "commit").resolve()
        assert reports == ["updated skills/commit"]

    def test_removes_dangling_symlink_for_deleted_skill(self, tmp_path):
        plugins = plugins_root(tmp_path)
        make_skill(plugins, "core", "commit")
        claude_dir = claude_root(tmp_path)
        sync_symlinks.sync_category(plugins, claude_dir, "skills")

        shutil.rmtree(plugins / "core" / "skills" / "commit")
        reports = sync_symlinks.sync_category(plugins, claude_dir, "skills")

        assert not (claude_dir / "skills" / "commit").is_symlink()
        assert reports == ["removed skills/commit (source no longer exists)"]

    def test_leaves_non_symlink_entry_alone(self, tmp_path):
        plugins = plugins_root(tmp_path)
        make_skill(plugins, "core", "commit")
        claude_dir = claude_root(tmp_path)
        skills_dir = claude_dir / "skills"
        skills_dir.mkdir(parents=True)
        (skills_dir / "commit").mkdir()
        (skills_dir / "commit" / "real-file.md").write_text("hand-written\n")

        reports = sync_symlinks.sync_category(plugins, claude_dir, "skills")

        assert (skills_dir / "commit" / "real-file.md").exists()
        assert reports == ["skipped skills/commit: exists and is not a symlink, leaving alone"]

    def test_migrates_whole_dir_symlink_to_real_directory_with_per_item_symlinks(self, tmp_path):
        plugins = plugins_root(tmp_path)
        make_command(plugins, "core", "chat")
        claude_dir = claude_root(tmp_path)
        claude_dir.mkdir()
        (claude_dir / "commands").symlink_to(plugins / "core" / "commands", target_is_directory=True)

        reports = sync_symlinks.sync_category(plugins, claude_dir, "commands")

        commands_dir = claude_dir / "commands"
        assert commands_dir.is_dir() and not commands_dir.is_symlink()
        assert (commands_dir / "chat.md").is_symlink()
        assert reports == ["created commands/chat.md"]


# -- summarize -----------------------------------------------------------------


class TestSummarize:
    def test_counts_each_kind(self):
        reports = [
            "created skills/a",
            "updated skills/b",
            "removed skills/c (source no longer exists)",
            "up to date skills/d",
            "skipped skills/e: exists and is not a symlink, leaving alone",
        ]

        assert sync_symlinks.summarize(reports) == "1 created, 1 updated, 1 removed, 2 skipped/up to date"
