# Generated by Claude Code

import importlib.util
import json
from pathlib import Path

_mod_path = Path(__file__).resolve().parent.parent / "nice-check.py"
_spec = importlib.util.spec_from_file_location("nice_check", _mod_path)
nice_check = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(nice_check)


def write(root: Path, rel: str, text: str) -> str:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return rel


def make_repo(root: Path, tracked=(), eol=None) -> nice_check.Repo:
    return nice_check.Repo(root, tuple(tracked), eol or {})


def make_skill(root: Path, plugin: str | None, name: str, frontmatter: str, body: str = "\n# Body\n") -> str:
    parent = f"plugins/{plugin}/skills" if plugin else ".claude/skills"
    return write(root, f"{parent}/{name}/SKILL.md", f"---\n{frontmatter}---\n{body}")


def make_rule(root: Path, plugin: str, name: str, frontmatter: str, body: str = "\n# Body\n") -> str:
    return write(root, f"plugins/{plugin}/rules/{name}.md", f"---\n{frontmatter}---\n{body}")


def managed(version: str = "1.0.0") -> str:
    return f'managed-by: https://example.invalid\nversion: "{version}"\nlast-change: "2026-01-01 12:00:00"\n'


def authored(name: str) -> str:
    return (
        f"name: {name}\n"
        "description: >-\n  Use when testing.\n"
        "disable-model-invocation: true\n"
        "user-invocable: true\n"
        "managed-by: https://example.invalid\n"
        'version: "1.0.0"\n'
        'last-change: "2026-01-01 12:00:00"\n'
    )


def repo_local(name: str) -> str:
    return (
        f"name: {name}\n"
        "description: >-\n  Use when testing.\n"
        "disable-model-invocation: true\n"
        "user-invocable: true\n"
        'last-change: "2026-01-01 12:00:00"\n'
    )


def messages(findings) -> list[str]:
    return [f"{finding.path}:{finding.line}: {finding.message}" for finding in findings]


def write_marketplace(root: Path, plugins: list[dict]) -> None:
    write(root, ".claude-plugin/marketplace.json", json.dumps({"name": "test", "plugins": plugins}))


# -- frontmatter parsing -----------------------------------------------------


class TestParseFrontmatter:
    def test_reads_plain_scalar_and_block_scalar(self):
        parsed = nice_check.parse_frontmatter("---\nname: demo\ndescription: >-\n  Line one\n  line two.\n---\nbody\n")

        assert parsed["name"].raw == "demo"
        assert parsed["name"].style is None
        assert parsed["description"].style == ">-"
        assert parsed["description"].raw == "Line one\nline two."

    def test_keeps_the_block_scalar_indicator_apart(self):
        parsed = nice_check.parse_frontmatter("---\ndescription: >\n  Text.\n---\n")

        assert parsed["description"].style == ">"

    def test_records_line_numbers(self):
        parsed = nice_check.parse_frontmatter('---\nname: demo\nversion: "1.0.0"\n---\n')

        assert parsed["name"].line == 2
        assert parsed["version"].line == 3

    def test_reads_a_list_value_without_confusing_it_for_a_scalar(self):
        parsed = nice_check.parse_frontmatter("---\nallowed-tools:\n  - Read\n  - Write\nname: demo\n---\n")

        assert parsed["allowed-tools"].raw == "- Read\n- Write"
        assert parsed["name"].raw == "demo"

    def test_rejects_a_file_without_frontmatter(self):
        try:
            nice_check.parse_frontmatter("# Title\n")
        except nice_check.FrontmatterError as exc:
            assert "does not open" in str(exc)
        else:
            raise AssertionError("expected FrontmatterError")

    def test_rejects_an_unterminated_block(self):
        try:
            nice_check.parse_frontmatter("---\nname: demo\n")
        except nice_check.FrontmatterError as exc:
            assert "never closed" in str(exc)
        else:
            raise AssertionError("expected FrontmatterError")


# -- A. plugin manifests -----------------------------------------------------


class TestCheckPluginManifests:
    def test_reports_a_description_that_drifted(self, tmp_path):
        write_marketplace(tmp_path, [{"name": "core", "source": "./plugins/core", "description": "One"}])
        write(tmp_path, "plugins/core/.claude-plugin/plugin.json", json.dumps({"name": "core", "description": "Two"}))

        findings = nice_check.check_plugin_manifests(make_repo(tmp_path))

        assert len(findings) == 1
        assert "description differs" in findings[0].message

    def test_accepts_identical_descriptions(self, tmp_path):
        write_marketplace(tmp_path, [{"name": "core", "source": "./plugins/core", "description": "Same"}])
        write(tmp_path, "plugins/core/.claude-plugin/plugin.json", json.dumps({"name": "core", "description": "Same"}))

        assert nice_check.check_plugin_manifests(make_repo(tmp_path)) == []

    def test_skips_a_plugin_whose_source_is_an_object(self, tmp_path):
        source = {"source": "github", "repo": "someone/skills"}
        write_marketplace(tmp_path, [{"name": "external", "source": source, "description": "Remote"}])
        (tmp_path / "plugins").mkdir()

        assert nice_check.check_plugin_manifests(make_repo(tmp_path)) == []

    def test_reports_a_plugin_directory_missing_from_the_marketplace(self, tmp_path):
        write_marketplace(tmp_path, [])
        (tmp_path / "plugins" / "orphan").mkdir(parents=True)

        findings = nice_check.check_plugin_manifests(make_repo(tmp_path))

        assert "plugins/orphan is not listed" in findings[0].message

    def test_reports_invalid_json_instead_of_raising(self, tmp_path):
        write(tmp_path, ".claude-plugin/marketplace.json", "{not json")

        findings = nice_check.check_plugin_manifests(make_repo(tmp_path))

        assert findings[0].severity == "error"
        assert "invalid JSON" in findings[0].message


# -- B. frontmatter of skills and rules --------------------------------------


class TestCheckSkillFrontmatter:
    def test_accepts_a_well_formed_skill(self, tmp_path):
        make_skill(tmp_path, "core", "demo", authored("demo"))

        assert nice_check.check_skill_frontmatter(make_repo(tmp_path)) == []

    def test_reports_a_name_that_does_not_match_the_directory(self, tmp_path):
        make_skill(tmp_path, "core", "demo", authored("other"))

        findings = nice_check.check_skill_frontmatter(make_repo(tmp_path))

        assert findings[0].severity == "error"
        assert "does not match the directory" in findings[0].message

    def test_reports_an_unquoted_argument_hint(self, tmp_path):
        make_skill(tmp_path, "core", "demo", authored("demo") + "argument-hint: [plan.md]\n")

        findings = nice_check.check_skill_frontmatter(make_repo(tmp_path))

        assert "argument-hint parses as a YAML list" in findings[0].message

    def test_accepts_a_quoted_argument_hint(self, tmp_path):
        make_skill(tmp_path, "core", "demo", authored("demo") + 'argument-hint: "[plan.md]"\n')

        assert nice_check.check_skill_frontmatter(make_repo(tmp_path)) == []

    def test_reports_a_description_that_keeps_its_trailing_newline(self, tmp_path):
        frontmatter = authored("demo").replace("description: >-", "description: >")
        make_skill(tmp_path, "core", "demo", frontmatter)

        findings = nice_check.check_skill_frontmatter(make_repo(tmp_path))

        assert "keeps a trailing newline" in findings[0].message

    def test_reports_missing_flags_and_managed_keys(self, tmp_path):
        make_skill(tmp_path, "core", "demo", "name: demo\ndescription: Short.\n")

        findings = nice_check.check_skill_frontmatter(make_repo(tmp_path))

        assert [finding.message for finding in findings] == [
            "disable-model-invocation is not set explicitly",
            "user-invocable is not set explicitly",
            "last-change is missing",
            "managed-by is missing",
            "version is missing",
        ]

    def test_reports_a_license_in_the_frontmatter(self, tmp_path):
        make_skill(tmp_path, "vendor", "demo", authored("demo") + "license: MIT\n")

        findings = nice_check.check_skill_frontmatter(make_repo(tmp_path))

        assert len(findings) == 1
        assert "license does not belong in frontmatter" in findings[0].message

    def test_holds_a_taken_over_skill_to_the_same_rules(self, tmp_path):
        frontmatter = "name: demo\ndescription: >\n  Text.\norigin: https://example.invalid\nlicense: MIT\n"
        make_skill(tmp_path, "vendor", "demo", frontmatter)

        findings = nice_check.check_skill_frontmatter(make_repo(tmp_path))

        assert [finding.message for finding in findings] == [
            "description uses `>`, which keeps a trailing newline; use `>-`",
            "disable-model-invocation is not set explicitly",
            "user-invocable is not set explicitly",
            "license does not belong in frontmatter; `origin` is what records where a file came from",
            "last-change is missing",
            "managed-by is missing",
            "version is missing",
        ]

    def test_still_checks_a_skill_that_only_records_its_origin(self, tmp_path):
        make_skill(tmp_path, "core", "demo", "name: demo\ndescription: >\n  Text.\norigin: https://example.invalid\n")

        findings = nice_check.check_skill_frontmatter(make_repo(tmp_path))

        assert "keeps a trailing newline" in findings[0].message

    def test_does_not_ask_a_repo_local_skill_for_managed_by(self, tmp_path):
        make_skill(tmp_path, None, "demo", repo_local("demo"))

        assert nice_check.check_skill_frontmatter(make_repo(tmp_path)) == []

    def test_reports_a_last_change_that_is_not_a_sql_timestamp(self, tmp_path):
        frontmatter = authored("demo").replace('"2026-01-01 12:00:00"', '"27.8.2026"')
        make_skill(tmp_path, "core", "demo", frontmatter)

        findings = nice_check.check_skill_frontmatter(make_repo(tmp_path))

        assert len(findings) == 1
        assert findings[0].message == "last-change '27.8.2026' is not YYYY-MM-DD HH:MM:SS"

    def test_accepts_an_unquoted_last_change(self, tmp_path):
        frontmatter = authored("demo").replace('"2026-01-01 12:00:00"', "2026-01-01 12:00:00")
        make_skill(tmp_path, "core", "demo", frontmatter)

        assert nice_check.check_skill_frontmatter(make_repo(tmp_path)) == []

    def test_asks_a_repo_local_skill_for_last_change(self, tmp_path):
        frontmatter = repo_local("demo").replace('last-change: "2026-01-01 12:00:00"\n', "")
        make_skill(tmp_path, None, "demo", frontmatter)

        findings = nice_check.check_skill_frontmatter(make_repo(tmp_path))

        assert [finding.message for finding in findings] == ["last-change is missing"]

    def test_asks_a_taken_over_skill_for_last_change(self, tmp_path):
        frontmatter = authored("demo").replace('last-change: "2026-01-01 12:00:00"\n', "")
        make_skill(tmp_path, "vendor", "demo", frontmatter + "origin: https://example.invalid\n")

        findings = nice_check.check_skill_frontmatter(make_repo(tmp_path))

        assert [finding.message for finding in findings] == ["last-change is missing"]

    def test_reports_a_skill_without_frontmatter_instead_of_raising(self, tmp_path):
        write(tmp_path, "plugins/core/skills/demo/SKILL.md", "# Demo\n")

        findings = nice_check.check_skill_frontmatter(make_repo(tmp_path))

        assert findings[0].severity == "error"
        assert "does not open" in findings[0].message


class TestCheckRuleFrontmatter:
    def test_accepts_a_well_formed_rule(self, tmp_path):
        make_rule(tmp_path, "core", "python", 'paths:\n  - "**/*.py"\n' + managed())

        assert nice_check.check_rule_frontmatter(make_repo(tmp_path)) == []

    def test_reports_missing_bookkeeping(self, tmp_path):
        make_rule(tmp_path, "core", "python", 'paths:\n  - "**/*.py"\n')

        findings = nice_check.check_rule_frontmatter(make_repo(tmp_path))

        assert [finding.message for finding in findings] == [
            "last-change is missing",
            "managed-by is missing",
            "version is missing",
        ]

    def test_reports_a_license_in_the_frontmatter(self, tmp_path):
        make_rule(tmp_path, "core", "python", managed() + "license: MIT\n")

        findings = nice_check.check_rule_frontmatter(make_repo(tmp_path))

        assert len(findings) == 1
        assert "license does not belong in frontmatter" in findings[0].message

    def test_does_not_ask_a_rule_for_a_name_or_the_invocation_flags(self, tmp_path):
        make_rule(tmp_path, "core", "python", "description: Python conventions.\n" + managed())

        assert nice_check.check_rule_frontmatter(make_repo(tmp_path)) == []

    def test_reports_a_rule_without_frontmatter_instead_of_raising(self, tmp_path):
        write(tmp_path, "plugins/core/rules/python.md", "# Python\n")

        findings = nice_check.check_rule_frontmatter(make_repo(tmp_path))

        assert findings[0].severity == "error"
        assert "does not open" in findings[0].message


# -- C. skill name collisions ------------------------------------------------


class TestCheckSkillCollisions:
    def test_reports_the_same_name_in_two_plugins(self, tmp_path):
        make_skill(tmp_path, "core", "shared", authored("shared"))
        make_skill(tmp_path, "lab", "shared", authored("shared"))

        findings = nice_check.check_skill_collisions(make_repo(tmp_path))

        assert findings[0].severity == "error"
        assert "plugins/lab/skills/shared/SKILL.md" in findings[0].message

    def test_accepts_distinct_names(self, tmp_path):
        make_skill(tmp_path, "core", "one", authored("one"))
        make_skill(tmp_path, "lab", "two", authored("two"))

        assert nice_check.check_skill_collisions(make_repo(tmp_path)) == []


# -- D. plugin README vs reality ---------------------------------------------


class TestCheckPluginReadmes:
    def test_accepts_a_skill_mentioned_only_as_a_slash_command(self, tmp_path):
        make_skill(tmp_path, "core", "demo", authored("demo"))
        write(tmp_path, "plugins/core/README.md", "# core\n\nType `/demo` to run it.\n")

        assert nice_check.check_plugin_readmes(make_repo(tmp_path)) == []

    def test_accepts_a_skill_mentioned_only_as_a_path(self, tmp_path):
        make_skill(tmp_path, "core", "demo", authored("demo"))
        write(tmp_path, "plugins/core/README.md", "# core\n\nSee skills/demo/SKILL.md.\n")

        assert nice_check.check_plugin_readmes(make_repo(tmp_path)) == []

    def test_reports_a_skill_the_readme_never_mentions(self, tmp_path):
        make_skill(tmp_path, "core", "demo", authored("demo"))
        write(tmp_path, "plugins/core/README.md", "# core\n\nNothing here.\n")

        findings = nice_check.check_plugin_readmes(make_repo(tmp_path))

        assert findings[0].message == "demo is not mentioned in the README"

    def test_reports_a_rule_the_readme_never_mentions(self, tmp_path):
        write(tmp_path, "plugins/core/rules/clean-code.md", "# Clean code\n")
        write(tmp_path, "plugins/core/README.md", "# core\n\nNothing here.\n")

        findings = nice_check.check_plugin_readmes(make_repo(tmp_path))

        assert findings[0].message == "clean-code is not mentioned in the README"

    def test_reports_a_readme_entry_with_nothing_behind_it(self, tmp_path):
        write(tmp_path, "plugins/core/README.md", "# core\n\n- `ghost` - long gone\n")

        findings = nice_check.check_plugin_readmes(make_repo(tmp_path))

        assert "README lists `ghost`" in findings[0].message

    def test_ignores_a_bullet_that_names_a_real_file(self, tmp_path):
        write(tmp_path, "plugins/core/scripts/install.sh", "#!/usr/bin/env bash\n")
        write(tmp_path, "plugins/core/README.md", "# core\n\n- `install.sh` - installs things\n")

        assert nice_check.check_plugin_readmes(make_repo(tmp_path)) == []


# -- E. dead relative links --------------------------------------------------


class TestCheckMarkdownLinks:
    def link_repo(self, tmp_path, rel: str, text: str) -> nice_check.Repo:
        tracked = [write(tmp_path, rel, text)]
        tracked.append(write(tmp_path, "plugins/core/README.md", "# core\n"))
        return make_repo(tmp_path, tracked)

    def test_reports_a_dotted_link_leaving_the_repo_into_nothing(self, tmp_path):
        repo = self.link_repo(tmp_path, "plugins/lab/skills/demo/SKILL.md", "See [rules](../../rules/clean-code.md).\n")

        findings = nice_check.check_markdown_links(repo)

        assert findings[0].severity == "error"
        assert findings[0].line == 1

    def test_accepts_a_dotted_link_that_resolves(self, tmp_path):
        repo = self.link_repo(tmp_path, "plugins/lab/README.md", "See [core](../core/README.md).\n")

        assert nice_check.check_markdown_links(repo) == []

    def test_ignores_illustrative_targets(self, tmp_path):
        body = "[text](url) [file.ts:42](file.ts#L42) [path/to/file.ext:42](path/to/file.ext#L42)\n"
        repo = self.link_repo(tmp_path, "plugins/core/rules/markdown-style.md", body)

        assert nice_check.check_markdown_links(repo) == []

    def test_checks_a_bare_target_starting_at_a_repo_root_entry(self, tmp_path):
        repo = self.link_repo(tmp_path, "README.md", "[core](plugins/core/README.md) [gone](plugins/gone/README.md)\n")

        findings = nice_check.check_markdown_links(repo)

        assert len(findings) == 1
        assert "plugins/gone/README.md" in findings[0].message

    def test_ignores_the_fragment_of_an_existing_target(self, tmp_path):
        repo = self.link_repo(tmp_path, "README.md", "[core](plugins/core/README.md#L4)\n")

        assert nice_check.check_markdown_links(repo) == []

    def test_ignores_external_links(self, tmp_path):
        repo = self.link_repo(tmp_path, "README.md", "[docs](https://example.invalid/x) [mail](mailto:a@b.c)\n")

        assert nice_check.check_markdown_links(repo) == []


# -- F. hook configuration ---------------------------------------------------


class TestCheckHookConfigs:
    def write_hooks(self, tmp_path, events: dict) -> nice_check.Repo:
        write(tmp_path, "plugins/core/hooks/hooks.json", json.dumps({"hooks": events}))
        return make_repo(tmp_path)

    def test_reports_a_matcher_used_twice_in_one_event(self, tmp_path):
        write(tmp_path, "plugins/core/hooks/one.sh", "")
        write(tmp_path, "plugins/core/hooks/two.sh", "")
        blocks = [
            {"matcher": "Edit|Write", "hooks": [{"command": "bash ${CLAUDE_PLUGIN_ROOT}/hooks/one.sh"}]},
            {"matcher": "Edit|Write", "hooks": [{"command": "bash ${CLAUDE_PLUGIN_ROOT}/hooks/two.sh"}]},
        ]
        repo = self.write_hooks(tmp_path, {"PostToolUse": blocks})

        findings = nice_check.check_hook_configs(repo)

        assert len(findings) == 1
        assert "is used twice" in findings[0].message

    def test_accepts_matchers_that_only_overlap(self, tmp_path):
        write(tmp_path, "plugins/core/hooks/one.sh", "")
        blocks = [
            {"matcher": "Edit|Write", "hooks": [{"command": "bash ${CLAUDE_PLUGIN_ROOT}/hooks/one.sh"}]},
            {"matcher": "Edit|Write|Bash", "hooks": [{"command": "bash ${CLAUDE_PLUGIN_ROOT}/hooks/one.sh"}]},
        ]
        repo = self.write_hooks(tmp_path, {"PostToolUse": blocks})

        assert nice_check.check_hook_configs(repo) == []

    def test_reports_a_script_that_is_not_there(self, tmp_path):
        blocks = [{"matcher": "Bash", "hooks": [{"command": "python3 ${CLAUDE_PLUGIN_ROOT}/hooks/gone.py"}]}]
        repo = self.write_hooks(tmp_path, {"PreToolUse": blocks})

        findings = nice_check.check_hook_configs(repo)

        assert "gone.py does not exist" in findings[0].message

    def test_expands_the_project_directory_variable(self, tmp_path):
        write(tmp_path, "scripts/sync.py", "")
        blocks = [{"hooks": [{"command": 'python3 "${CLAUDE_PROJECT_DIR}/scripts/sync.py"'}]}]
        repo = self.write_hooks(tmp_path, {"UserPromptSubmit": blocks})

        assert nice_check.check_hook_configs(repo) == []

    def test_reports_invalid_json_instead_of_raising(self, tmp_path):
        write(tmp_path, "plugins/core/hooks/hooks.json", "{oops")

        findings = nice_check.check_hook_configs(make_repo(tmp_path))

        assert findings[0].severity == "error"
        assert "invalid JSON" in findings[0].message


# -- G. hook exit codes ------------------------------------------------------


class TestCheckHookExitCodes:
    def test_reports_exit_one_in_a_hook(self, tmp_path):
        tracked = [write(tmp_path, "plugins/core/hooks/check.sh", "#!/usr/bin/env bash\nexit 1\n")]

        findings = nice_check.check_hook_exit_codes(make_repo(tmp_path, tracked))

        assert findings[0].line == 2

    def test_reports_sys_exit_one_in_a_hook(self, tmp_path):
        tracked = [write(tmp_path, "plugins/core/hooks/check.py", "import sys\nsys.exit(1)\n")]

        findings = nice_check.check_hook_exit_codes(make_repo(tmp_path, tracked))

        assert findings[0].line == 2

    def test_accepts_the_allowed_exit_codes(self, tmp_path):
        tracked = [write(tmp_path, "plugins/core/hooks/check.sh", "exit 0\nexit 2\n")]

        assert nice_check.check_hook_exit_codes(make_repo(tmp_path, tracked)) == []

    def test_leaves_hook_tests_alone(self, tmp_path):
        tracked = [write(tmp_path, "plugins/core/hooks/tests/test_check.py", "sys.exit(1)\n")]

        assert nice_check.check_hook_exit_codes(make_repo(tmp_path, tracked)) == []


# -- H. references between skills --------------------------------------------


class TestCheckSkillCrossReferences:
    def test_reports_a_skill_pointing_at_another_one(self, tmp_path):
        make_skill(tmp_path, "core", "one", authored("one"), "\nRun /two afterwards.\n")
        make_skill(tmp_path, "core", "two", authored("two"))

        findings = nice_check.check_skill_cross_references(make_repo(tmp_path))

        assert len(findings) == 1
        assert "mentions the 'two' skill" in findings[0].message

    def test_reports_a_backticked_mention(self, tmp_path):
        make_skill(tmp_path, "core", "one", authored("one"), "\nSee the `two` skill.\n")
        make_skill(tmp_path, "core", "two", authored("two"))

        assert len(nice_check.check_skill_cross_references(make_repo(tmp_path))) == 1

    def test_lets_a_skill_name_itself(self, tmp_path):
        make_skill(tmp_path, "core", "one", authored("one"), "\nInvoke /one to start.\n")

        assert nice_check.check_skill_cross_references(make_repo(tmp_path)) == []

    def test_does_not_match_a_longer_skill_name(self, tmp_path):
        make_skill(tmp_path, "core", "one", authored("one"))
        make_skill(tmp_path, "core", "one-more", authored("one-more"), "\nInvoke /one-more.\n")

        assert nice_check.check_skill_cross_references(make_repo(tmp_path)) == []

    def test_reports_a_taken_over_skill_pointing_at_another_one(self, tmp_path):
        make_skill(tmp_path, "vendor", "one", authored("one") + "origin: https://example.invalid\n", "\nSee /two.\n")
        make_skill(tmp_path, "core", "two", authored("two"))

        assert len(nice_check.check_skill_cross_references(make_repo(tmp_path))) == 1


# -- I. text hygiene ---------------------------------------------------------


class TestParseEol:
    def test_keeps_a_crlf_worktree_entry(self):
        lines = [
            "i/lf    w/crlf  attr/                \tdocs/win.md",
            "i/lf    w/lf    attr/                \tREADME.md",
        ]

        assert nice_check.parse_eol(lines) == {"docs/win.md": "crlf", "README.md": "lf"}


class TestCheckTextHygiene:
    def test_reports_crlf_line_endings(self, tmp_path):
        tracked = [write(tmp_path, "a.sh", "echo hi\n")]

        findings = nice_check.check_text_hygiene(make_repo(tmp_path, tracked, {"a.sh": "crlf"}))

        assert "CRLF" in findings[0].message

    def test_reports_trailing_whitespace_outside_markdown(self, tmp_path):
        tracked = [write(tmp_path, "a.sh", "echo hi  \n")]

        findings = nice_check.check_text_hygiene(make_repo(tmp_path, tracked))

        assert messages(findings) == ["a.sh:1: trailing whitespace"]

    def test_leaves_trailing_whitespace_in_markdown_alone(self, tmp_path):
        tracked = [write(tmp_path, "a.md", "line  \n")]

        assert nice_check.check_text_hygiene(make_repo(tmp_path, tracked)) == []

    def test_reports_a_long_line_in_a_shell_script(self, tmp_path):
        tracked = [write(tmp_path, "a.ps1", "#" * 121 + "\n")]

        findings = nice_check.check_text_hygiene(make_repo(tmp_path, tracked))

        assert "121 characters" in findings[0].message

    def test_leaves_long_python_lines_to_ruff(self, tmp_path):
        tracked = [write(tmp_path, "a.py", "#" * 200 + "\n")]

        assert nice_check.check_text_hygiene(make_repo(tmp_path, tracked)) == []

    def test_reports_a_missing_final_newline(self, tmp_path):
        tracked = [write(tmp_path, "a.sh", "echo hi")]

        findings = nice_check.check_text_hygiene(make_repo(tmp_path, tracked))

        assert "does not end with a newline" in findings[0].message

    def test_reports_accented_letters(self, tmp_path):
        # The accents are \u escapes so this test file itself stays ASCII - nice-check scans its own repo.
        tracked = [write(tmp_path, "a.md", "kontrola nen\u00ed hotov\u00e1\n")]

        findings = nice_check.check_text_hygiene(make_repo(tmp_path, tracked))

        assert "non-ASCII letters" in findings[0].message

    def test_accepts_dashes_arrows_and_math_signs(self, tmp_path):
        tracked = [write(tmp_path, "a.md", "a — b → c ≠ d\n")]

        assert nice_check.check_text_hygiene(make_repo(tmp_path, tracked)) == []

    def test_reports_a_generator_placeholder(self, tmp_path):
        # Split so the literal phrase never appears in this file either - the check
        # matches "Add your" and "description here" across any run of whitespace.
        tracked = [write(tmp_path, "a.md", "Add your " + "description here\n")]

        findings = nice_check.check_text_hygiene(make_repo(tmp_path, tracked))

        assert "generator placeholder" in findings[0].message

    def test_reports_a_file_that_is_not_utf8(self, tmp_path):
        (tmp_path / "a.md").write_bytes(b"\xff\xfe binary\n")

        findings = nice_check.check_text_hygiene(make_repo(tmp_path, ["a.md"]))

        assert findings[0].severity == "error"
        assert "cannot read the file" in findings[0].message


# -- J. stray tracked files --------------------------------------------------


class TestCheckStrayTrackedFiles:
    def test_reports_a_tracked_plan(self, tmp_path):
        findings = nice_check.check_stray_tracked_files(make_repo(tmp_path, [".claude/plans/x.md", "README.md"]))

        assert messages(findings) == [
            ".claude/plans/x.md:None: plans are local scratch; .claude/plans/ must stay untracked"
        ]

    def test_accepts_a_repo_without_tracked_plans(self, tmp_path):
        assert nice_check.check_stray_tracked_files(make_repo(tmp_path, ["README.md"])) == []


# -- whole run ---------------------------------------------------------------


class TestRunChecks:
    def test_broken_input_is_a_finding_and_the_other_checks_still_run(self, tmp_path):
        write(tmp_path, ".claude-plugin/marketplace.json", "{broken\n")
        write(tmp_path, "plugins/core/skills/demo/SKILL.md", "# no frontmatter\n")
        tracked = [".claude-plugin/marketplace.json", write(tmp_path, "a.sh", "echo hi  \n")]

        findings = nice_check.run_checks(make_repo(tmp_path, tracked))

        assert [(finding.check, finding.severity) for finding in findings] == [
            ("A", "error"),
            ("B", "error"),
            ("D", "warning"),
            ("I", "warning"),
        ]
