# Generated by Claude Code

import importlib.util
from pathlib import Path

import pytest

# Module has a hyphen in its filename, so we need importlib to import it.
_mod_path = Path(__file__).resolve().parent.parent / "install-rules.py"
_spec = importlib.util.spec_from_file_location("install_rules", _mod_path)
install_rules = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(install_rules)

OTHER_REPO = "https://github.com/someone-else/other-repo"


def write_rule(
    path: Path, *, version: str | None, managed_by: str | None = install_rules.MANAGED_BY, body: str = "content"
) -> None:
    frontmatter_lines = []
    if managed_by is not None:
        frontmatter_lines.append(f"managed-by: {managed_by}")
    if version is not None:
        frontmatter_lines.append(f'version: "{version}"')
    frontmatter = f"---\n{chr(10).join(frontmatter_lines)}\n---\n" if frontmatter_lines else ""
    path.write_text(f"{frontmatter}{body}\n")


# -- extract_frontmatter ---------------------------------------------------------


class TestExtractFrontmatter:
    def test_extracts_block(self):
        text = '---\npaths:\n  - "**/*.py"\nversion: "1.0.0"\n---\n# Title\n'
        assert install_rules.extract_frontmatter(text) == ["paths:", '  - "**/*.py"', 'version: "1.0.0"']

    def test_no_opening_delimiter(self):
        assert install_rules.extract_frontmatter("# No frontmatter\n") is None

    def test_no_closing_delimiter(self):
        assert install_rules.extract_frontmatter('---\nversion: "1.0.0"\n') is None

    def test_empty_frontmatter(self):
        assert install_rules.extract_frontmatter("---\n---\ncontent\n") == []


# -- frontmatter_value -------------------------------------------------------------


class TestFrontmatterValue:
    def test_finds_quoted_value(self):
        assert install_rules.frontmatter_value(['version: "1.2.3"'], "version") == "1.2.3"

    def test_finds_unquoted_value(self):
        assert (
            install_rules.frontmatter_value(["managed-by: https://example.com/repo"], "managed-by")
            == "https://example.com/repo"
        )

    def test_ignores_other_keys(self):
        lines = ["paths:", '  - "**/*.py"', 'version: "2.0.1"']
        assert install_rules.frontmatter_value(lines, "version") == "2.0.1"

    def test_missing_key(self):
        assert install_rules.frontmatter_value(["paths:", '  - "**/*.py"'], "version") is None


# -- parse_version ----------------------------------------------------------------


class TestParseVersion:
    def test_parses_version(self):
        assert install_rules.parse_version(['version: "1.2.3"']) == install_rules.Version(1, 2, 3)

    def test_missing_version(self):
        assert install_rules.parse_version(["paths:", '  - "**/*.py"']) is None


# -- install_rule ---------------------------------------------------------------


class TestInstallRule:
    def test_installs_when_missing(self, tmp_path):
        source = tmp_path / "source"
        source.mkdir()
        target = tmp_path / "target"
        target.mkdir()

        rule = source / "rule.md"
        write_rule(rule, version="1.0.0")

        result = install_rules.install_rule(rule, target)

        assert (target / "rule.md").read_text() == rule.read_text()
        assert "installed rule.md (1.0.0)" == result

    def test_updates_when_source_is_newer(self, tmp_path):
        source = tmp_path / "source"
        source.mkdir()
        target = tmp_path / "target"
        target.mkdir()

        rule = source / "rule.md"
        write_rule(rule, version="1.1.0", body="new content")
        write_rule(target / "rule.md", version="1.0.0", body="old content")

        result = install_rules.install_rule(rule, target)

        assert (target / "rule.md").read_text() == rule.read_text()
        assert result == "updated rule.md: 1.0.0 -> 1.1.0"

    def test_skips_when_up_to_date(self, tmp_path):
        source = tmp_path / "source"
        source.mkdir()
        target = tmp_path / "target"
        target.mkdir()

        rule = source / "rule.md"
        write_rule(rule, version="1.0.0", body="new content")
        target_rule = target / "rule.md"
        write_rule(target_rule, version="1.0.0", body="old content")
        original_content = target_rule.read_text()

        result = install_rules.install_rule(rule, target)

        assert target_rule.read_text() == original_content
        assert result == "up to date rule.md (1.0.0)"

    def test_skips_when_target_has_no_managed_by(self, tmp_path):
        source = tmp_path / "source"
        source.mkdir()
        target = tmp_path / "target"
        target.mkdir()

        rule = source / "rule.md"
        write_rule(rule, version="1.0.0")
        (target / "rule.md").write_text("hand-written content\n")

        result = install_rules.install_rule(rule, target)

        assert (target / "rule.md").read_text() == "hand-written content\n"
        assert result == "skipped rule.md: not managed by this repo, not overwriting"

    def test_skips_when_target_has_different_managed_by(self, tmp_path):
        source = tmp_path / "source"
        source.mkdir()
        target = tmp_path / "target"
        target.mkdir()

        rule = source / "rule.md"
        write_rule(rule, version="1.0.0")
        target_rule = target / "rule.md"
        write_rule(target_rule, version="99.0.0", managed_by=OTHER_REPO, body="foreign content")

        result = install_rules.install_rule(rule, target)

        assert target_rule.read_text() == f'---\nmanaged-by: {OTHER_REPO}\nversion: "99.0.0"\n---\nforeign content\n'
        assert result == "skipped rule.md: not managed by this repo, not overwriting"

    def test_updates_when_managed_but_version_unparseable(self, tmp_path):
        source = tmp_path / "source"
        source.mkdir()
        target = tmp_path / "target"
        target.mkdir()

        rule = source / "rule.md"
        write_rule(rule, version="1.0.0")
        target_rule = target / "rule.md"
        write_rule(target_rule, version=None, body="corrupted")

        result = install_rules.install_rule(rule, target)

        assert target_rule.read_text() == rule.read_text()
        assert result == "updated rule.md: unknown -> 1.0.0"


# -- remove_orphaned_rule ------------------------------------------------------


class TestRemoveOrphanedRule:
    def test_removes_rule_managed_by_this_repo(self, tmp_path):
        orphan = tmp_path / "hooks.md"
        write_rule(orphan, version="1.0.0")

        result = install_rules.remove_orphaned_rule(orphan)

        assert not orphan.exists()
        assert result == "removed hooks.md: no longer in plugin"

    def test_keeps_rule_managed_by_another_repo(self, tmp_path):
        foreign = tmp_path / "hooks.md"
        write_rule(foreign, version="1.0.0", managed_by=OTHER_REPO, body="foreign content")
        original_content = foreign.read_text()

        result = install_rules.remove_orphaned_rule(foreign)

        assert foreign.read_text() == original_content
        assert result is None

    def test_keeps_rule_without_frontmatter(self, tmp_path):
        hand_written = tmp_path / "hooks.md"
        hand_written.write_text("hand-written content\n")

        result = install_rules.remove_orphaned_rule(hand_written)

        assert hand_written.read_text() == "hand-written content\n"
        assert result is None


# -- replace_stale_symlink -----------------------------------------------------


class TestReplaceStaleSymlink:
    def test_removes_symlink_without_touching_its_target(self, tmp_path):
        old_plugin_rules = tmp_path / "old-plugin-rules"
        old_plugin_rules.mkdir()
        (old_plugin_rules / "python.md").write_text("original plugin content\n")

        target_dir = tmp_path / "project" / ".claude" / "rules" / "plugins" / "nicecode" / "core"
        target_dir.parent.mkdir(parents=True)
        target_dir.symlink_to(old_plugin_rules)

        install_rules.replace_stale_symlink(target_dir)

        assert not target_dir.is_symlink()
        assert not target_dir.exists()
        assert (old_plugin_rules / "python.md").read_text() == "original plugin content\n"

    def test_noop_for_real_directory(self, tmp_path):
        target_dir = tmp_path / "target"
        target_dir.mkdir()

        install_rules.replace_stale_symlink(target_dir)

        assert target_dir.is_dir()
        assert not target_dir.is_symlink()


# -- main (integration) ----------------------------------------------------------


class TestMain:
    def test_installs_all_rules_into_project_dir(self, tmp_path, monkeypatch):
        plugin_root = tmp_path / "plugin"
        (plugin_root / "rules").mkdir(parents=True)
        write_rule(plugin_root / "rules" / "a.md", version="1.0.0")
        write_rule(plugin_root / "rules" / "b.md", version="1.0.0")

        project_dir = tmp_path / "project"
        project_dir.mkdir()

        monkeypatch.setattr(install_rules, "__file__", str(plugin_root / "scripts" / "install-rules.py"))
        monkeypatch.setattr("sys.argv", ["install-rules.py", str(project_dir), "--scope", "project"])

        install_rules.main()

        target_dir = project_dir / ".claude" / "rules" / "plugins" / "nicecode" / "core"
        assert (target_dir / "a.md").exists()
        assert (target_dir / "b.md").exists()

    def test_defaults_to_current_working_directory(self, tmp_path, monkeypatch):
        plugin_root = tmp_path / "plugin"
        (plugin_root / "rules").mkdir(parents=True)
        write_rule(plugin_root / "rules" / "a.md", version="1.0.0")

        project_dir = tmp_path / "project"
        project_dir.mkdir()

        monkeypatch.setattr(install_rules, "__file__", str(plugin_root / "scripts" / "install-rules.py"))
        monkeypatch.setattr("sys.argv", ["install-rules.py", "--scope", "project"])
        monkeypatch.chdir(project_dir)

        install_rules.main()

        target_dir = project_dir / ".claude" / "rules" / "plugins" / "nicecode" / "core"
        assert (target_dir / "a.md").exists()

    def test_installs_into_home_directory_for_user_scope(self, tmp_path, monkeypatch):
        plugin_root = tmp_path / "plugin"
        (plugin_root / "rules").mkdir(parents=True)
        write_rule(plugin_root / "rules" / "a.md", version="1.0.0")

        fake_home = tmp_path / "home"
        fake_home.mkdir()

        monkeypatch.setattr(install_rules, "__file__", str(plugin_root / "scripts" / "install-rules.py"))
        monkeypatch.setattr("sys.argv", ["install-rules.py", "--scope", "user"])
        monkeypatch.setattr(Path, "home", lambda: fake_home)

        install_rules.main()

        target_dir = fake_home / ".claude" / "rules" / "plugins" / "nicecode" / "core"
        assert (target_dir / "a.md").exists()

    def test_ignores_project_dir_argument_for_user_scope(self, tmp_path, monkeypatch):
        plugin_root = tmp_path / "plugin"
        (plugin_root / "rules").mkdir(parents=True)
        write_rule(plugin_root / "rules" / "a.md", version="1.0.0")

        project_dir = tmp_path / "project"
        project_dir.mkdir()
        fake_home = tmp_path / "home"
        fake_home.mkdir()

        monkeypatch.setattr(install_rules, "__file__", str(plugin_root / "scripts" / "install-rules.py"))
        monkeypatch.setattr("sys.argv", ["install-rules.py", str(project_dir), "--scope", "user"])
        monkeypatch.setattr(Path, "home", lambda: fake_home)

        install_rules.main()

        assert not (project_dir / ".claude").exists()
        assert (fake_home / ".claude" / "rules" / "plugins" / "nicecode" / "core" / "a.md").exists()

    def test_removes_orphan_but_keeps_foreign_rule(self, tmp_path, monkeypatch):
        plugin_root = tmp_path / "plugin"
        (plugin_root / "rules").mkdir(parents=True)
        write_rule(plugin_root / "rules" / "a.md", version="1.0.0")

        project_dir = tmp_path / "project"
        target_dir = project_dir / ".claude" / "rules" / "plugins" / "nicecode" / "core"
        target_dir.mkdir(parents=True)
        write_rule(target_dir / "gone.md", version="1.0.0")
        write_rule(target_dir / "mine.md", version="1.0.0", managed_by=OTHER_REPO)

        monkeypatch.setattr(install_rules, "__file__", str(plugin_root / "scripts" / "install-rules.py"))
        monkeypatch.setattr("sys.argv", ["install-rules.py", str(project_dir), "--scope", "project"])

        install_rules.main()

        assert (target_dir / "a.md").exists()
        assert not (target_dir / "gone.md").exists()
        assert (target_dir / "mine.md").exists()

    def test_requires_scope_argument(self, tmp_path, monkeypatch):
        project_dir = tmp_path / "project"
        project_dir.mkdir()

        monkeypatch.setattr("sys.argv", ["install-rules.py", str(project_dir)])

        with pytest.raises(SystemExit, match="2"):
            install_rules.main()

    def test_exits_when_plugin_rules_dir_missing(self, tmp_path, monkeypatch):
        plugin_root = tmp_path / "plugin"
        plugin_root.mkdir()
        project_dir = tmp_path / "project"
        project_dir.mkdir()

        monkeypatch.setattr(install_rules, "__file__", str(plugin_root / "scripts" / "install-rules.py"))
        monkeypatch.setattr("sys.argv", ["install-rules.py", str(project_dir), "--scope", "project"])

        with pytest.raises(SystemExit, match="1"):
            install_rules.main()

    def test_migrates_stale_directory_symlink_from_old_installation(self, tmp_path, monkeypatch):
        plugin_root = tmp_path / "plugin"
        (plugin_root / "rules").mkdir(parents=True)
        write_rule(plugin_root / "rules" / "a.md", version="1.0.0")

        old_plugin_rules = tmp_path / "old-plugin-version" / "rules"
        old_plugin_rules.mkdir(parents=True)
        (old_plugin_rules / "a.md").write_text("stale plugin content\n")

        project_dir = tmp_path / "project"
        target_dir = project_dir / ".claude" / "rules" / "plugins" / "nicecode" / "core"
        target_dir.parent.mkdir(parents=True)
        target_dir.symlink_to(old_plugin_rules)

        monkeypatch.setattr(install_rules, "__file__", str(plugin_root / "scripts" / "install-rules.py"))
        monkeypatch.setattr("sys.argv", ["install-rules.py", str(project_dir), "--scope", "project"])

        install_rules.main()

        assert not target_dir.is_symlink()
        assert target_dir.is_dir()
        assert (target_dir / "a.md").read_text() == (plugin_root / "rules" / "a.md").read_text()
        assert (old_plugin_rules / "a.md").read_text() == "stale plugin content\n"
