# Generated by Claude Code

import importlib
import json
import os
import pytest
from pathlib import Path


# Module has a hyphen in its filename, so we need importlib to import it.
_mod_path = Path(__file__).resolve().parent.parent / "install-rules.py"
_spec = importlib.util.spec_from_file_location("install_rules", _mod_path)
install_rules = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(install_rules)

install_rules.DEBUG = True
install_rules.LOG_FILE = Path(os.devnull)

PLUGIN_KEY = "core@nicecode"
RULES_SUBDIR = Path("plugins") / "nicecode" / "core"


# -- helpers ------------------------------------------------------------------


def write_config(project_dir: Path, enabled_plugins: dict, *, local: bool = False) -> None:
    config_dir = project_dir / ".claude"
    config_dir.mkdir(parents=True, exist_ok=True)
    filename = "settings.local.json" if local else "settings.json"
    (config_dir / filename).write_text(json.dumps({"enabledPlugins": enabled_plugins}))


def setup_main_env(monkeypatch, tmp_path: Path) -> tuple[Path, Path]:
    """Create plugin_root (with rules/) and project_dir, set env vars."""
    plugin_root = tmp_path / "plugin"
    plugin_root.mkdir()
    (plugin_root / "rules").mkdir()

    project_dir = tmp_path / "project"
    project_dir.mkdir()

    monkeypatch.setenv("CLAUDE_PLUGIN_ROOT", str(plugin_root))
    monkeypatch.setenv("CLAUDE_PROJECT_DIR", str(project_dir))
    return plugin_root, project_dir


# -- is_plugin_enabled_in_project ---------------------------------------------


class TestIsPluginEnabledInProject:
    def test_enabled(self, tmp_path):
        write_config(tmp_path, {PLUGIN_KEY: True})
        assert install_rules.is_plugin_enabled_in_project(tmp_path) is True

    def test_disabled(self, tmp_path):
        write_config(tmp_path, {PLUGIN_KEY: False})
        assert install_rules.is_plugin_enabled_in_project(tmp_path) is False

    def test_plugin_missing(self, tmp_path):
        write_config(tmp_path, {"other@plugin": True})
        assert install_rules.is_plugin_enabled_in_project(tmp_path) is False

    def test_no_config_file(self, tmp_path):
        assert install_rules.is_plugin_enabled_in_project(tmp_path) is False

    def test_malformed_json(self, tmp_path):
        config_dir = tmp_path / ".claude"
        config_dir.mkdir(parents=True)
        (config_dir / "settings.json").write_text("{bad json")
        assert install_rules.is_plugin_enabled_in_project(tmp_path) is False

    def test_missing_enabled_plugins_key(self, tmp_path):
        config_dir = tmp_path / ".claude"
        config_dir.mkdir(parents=True)
        (config_dir / "settings.json").write_text(json.dumps({"other": "data"}))
        assert install_rules.is_plugin_enabled_in_project(tmp_path) is False

    def test_enabled_in_local_only(self, tmp_path):
        write_config(tmp_path, {PLUGIN_KEY: True}, local=True)
        assert install_rules.is_plugin_enabled_in_project(tmp_path) is True

    def test_enabled_in_settings_disabled_in_local(self, tmp_path):
        write_config(tmp_path, {PLUGIN_KEY: True})
        write_config(tmp_path, {PLUGIN_KEY: False}, local=True)
        assert install_rules.is_plugin_enabled_in_project(tmp_path) is True

    def test_disabled_in_both(self, tmp_path):
        write_config(tmp_path, {PLUGIN_KEY: False})
        write_config(tmp_path, {PLUGIN_KEY: False}, local=True)
        assert install_rules.is_plugin_enabled_in_project(tmp_path) is False


# -- link_rules ---------------------------------------------------------------


class TestLinkRules:
    def test_creates_symlink(self, tmp_path):
        plugin_rules = tmp_path / "plugin" / "rules"
        plugin_rules.mkdir(parents=True)
        project_rules = tmp_path / "project" / ".claude" / "rules" / RULES_SUBDIR

        install_rules.link_rules(plugin_rules, project_rules)

        assert project_rules.is_symlink()
        assert project_rules.resolve() == plugin_rules.resolve()

    def test_replaces_wrong_symlink(self, tmp_path):
        plugin_rules = tmp_path / "plugin" / "rules"
        plugin_rules.mkdir(parents=True)
        old_target = tmp_path / "old"
        old_target.mkdir()

        project_rules = tmp_path / "project" / ".claude" / "rules" / RULES_SUBDIR
        project_rules.parent.mkdir(parents=True)
        project_rules.symlink_to(old_target)

        install_rules.link_rules(plugin_rules, project_rules)

        assert project_rules.resolve() == plugin_rules.resolve()

    def test_noop_when_correct(self, tmp_path):
        plugin_rules = tmp_path / "plugin" / "rules"
        plugin_rules.mkdir(parents=True)

        project_rules = tmp_path / "project" / ".claude" / "rules" / RULES_SUBDIR
        project_rules.parent.mkdir(parents=True)
        project_rules.symlink_to(plugin_rules)

        install_rules.link_rules(plugin_rules, project_rules)

        assert project_rules.is_symlink()
        assert project_rules.resolve() == plugin_rules.resolve()


# -- main (integration) -------------------------------------------------------


class TestMain:
    def test_creates_symlink(self, tmp_path, monkeypatch):
        plugin_root, project_dir = setup_main_env(monkeypatch, tmp_path)
        write_config(project_dir, {PLUGIN_KEY: True})

        install_rules.main()

        symlink = project_dir / ".claude" / "rules" / RULES_SUBDIR
        assert symlink.is_symlink()
        assert symlink.resolve() == (plugin_root / "rules").resolve()

    def test_noop_when_plugin_disabled(self, tmp_path, monkeypatch):
        plugin_root, project_dir = setup_main_env(monkeypatch, tmp_path)
        write_config(project_dir, {PLUGIN_KEY: False})

        install_rules.main()

        assert not (project_dir / ".claude" / "rules" / RULES_SUBDIR).exists()

    def test_exits_when_env_var_missing(self, monkeypatch):
        monkeypatch.delenv("CLAUDE_PLUGIN_ROOT", raising=False)
        monkeypatch.delenv("CLAUDE_PROJECT_DIR", raising=False)

        with pytest.raises(SystemExit, match="1"):
            install_rules.main()
